# SCSSLint
# https://github.com/brigade/scss-lint
#
# default options:
# https://github.com/brigade/scss-lint/blob/master/config/default.yml

exclude:
  - 'client/stylesheets/vendors/**'

linters:

  Indentation:
    character: tab
    width: 1

  ElsePlacement:
    style: new_line

  PropertySortOrder:
    enabled: false
